# Generated by Django 5.0.6 on 2024-06-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0002_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_img')),
            ],
        ),
    ]
