# Generated by Django 5.0.6 on 2024-06-28 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0003_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
