# Generated by Django 5.0.6 on 2024-06-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0005_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='TECH_KNOWLEDGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='tech_stack',
        ),
    ]
