# Generated by Django 5.0.6 on 2024-06-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0006_tech_knowledge_delete_tech_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech_knowledge',
            name='live_demo_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
