# Generated by Django 5.0.6 on 2024-06-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0007_tech_knowledge_live_demo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech_knowledge',
            name='git_url',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
