# Generated by Django 5.0.6 on 2024-06-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_manager', '0008_tech_knowledge_git_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech_knowledge',
            name='git_url',
        ),
        migrations.RemoveField(
            model_name='tech_knowledge',
            name='live_demo_url',
        ),
        migrations.AddField(
            model_name='project',
            name='git_url',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='live_demo_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
